package:
  name: pytorch-sparse
  version: 0.6.17

source:
  path: ../..

requirements:
  build:
    - {{ compiler('c') }}  # [win]

  host:
    - pip
    - python {{ environ.get('PYTHON_VERSION') }}
    - {{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}
    - {{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}

  run:
    - scipy
    - pytorch-scatter
    - python {{ environ.get('PYTHON_VERSION') }}
    - {{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}
    - {{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}

build:
  string: py{{ environ.get('PYTHON_VERSION').replace('.', '') }}_torch_{{ environ['TORCH_VERSION'] }}_{{ environ['CUDA_VERSION'] }}
  script_env:
    - FORCE_CUDA
    - TORCH_CUDA_ARCH_LIST
    - WITH_METIS=1
  preserve_egg_dir: True

test:
  imports:
    - torch_sparse

about:
  home: https://github.com/rusty1s/pytorch_sparse
  license: MIT
  summary: PyTorch Extension Library of Optimized Autograd Sparse Matrix Operations
